# Generated by Django 6.0.5 on 2026-06-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_ingredientcatalog_ingredientalias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientalias',
            old_name='alias',
            new_name='ingredient_name',
        ),
        migrations.RemoveField(
            model_name='ingredientalias',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientalias',
            name='alias_name',
            field=models.CharField(db_index=True, default='', max_length=80),
            preserve_default=False,
        ),
    ]
