# Generated by Django 6.0.5 on 2026-05-14 05:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_save_count_savedrecipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedRecipe',
            new_name='RecipeSave',
        ),
    ]
