# Generated by Django 6.0.5 on 2026-05-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
