# Generated by Django 6.0.5 on 2026-05-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_tag_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_type',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
