# Generated by Django 6.0.5 on 2026-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
