# Generated by Django 5.2.12 on 2026-06-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', '시스템'), ('like', '좋아요'), ('comment', '댓글'), ('reply', '답글'), ('follow', '팔로우')], max_length=40),
        ),
    ]
